apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sc-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-sc
  hostPath:
    path: /var/k8s/local-sc     # каталог на ноде
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-sc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      labels:
        app: data-exchange-sc
    spec:
      containers:
        - name: busybox-writer
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "writer started"
              while true; do
                date +"%F %T: heartbeat" >> /data/exchange.log
                sleep 5
              done
          volumeMounts:
            - name: data
              mountPath: /data
        - name: multitool-reader
          image: wbitt/network-multitool:alpine-minimal
          command: ["/bin/sh","-c"]
          args: ["tail -F /data/exchange.log"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-sc-pvc
