apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
  labels:
    app: data-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: busybox-writer
          image: busybox:1.36
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "writer started"
              while true; do
                date +"%F %T: heartbeat" >> /shared/exchange.log
                sleep 5
              done
        - name: multitool-reader
          image: wbitt/network-multitool:alpine-minimal
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          command: ["/bin/sh","-c"]
          args: ["sleep infinity"]
