apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    pv: local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""        
  hostPath:
    path: /var/k8s/pv-local   # каталог на ноде
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: local-pv            # привязка к PV по метке
  storageClassName: ""        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-pvc-demo
  labels:
    app: pv-pvc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-pvc-demo
  template:
    metadata:
      labels:
        app: pv-pvc-demo
    spec:
      containers:
        - name: busybox-writer
          image: busybox:1.36
          volumeMounts:
            - name: data
              mountPath: /data
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "writer started"
              while true; do
                date +"%F %T: heartbeat" >> /data/exchange.log
                sleep 5
              done
        - name: multitool-reader
          image: wbitt/network-multitool:alpine-minimal
          volumeMounts:
            - name: data
              mountPath: /data
          command: ["/bin/sh","-c"]
          args: ["sleep infinity"]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-pvc
